config/routes.rb
Elotalks::Application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/log_out', to: 'sessions#destroy', as: 'log_out'

  resources :sessions, only: [:create]

  get 'slug_available' => 'talks#slug_available', as: 'slug_available'

  resources :talks, only: [:new, :create, :show, :index] do
    resources :votes, only: :create
  end

  root 'talks#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.persisted?
      can :create, Talk
    end
  end
end

app/models/audience.rb
class Audience < ActiveRecord::Base
  has_and_belongs_to_many :talks
end

app/models/audience_talk.rb
class AudienceTalk < ActiveRecord::Base
  belongs_to :talk
  belongs_to :audience
end

app/models/reference.rb
class Reference < ActiveRecord::Base
  belongs_to :talk
end

app/models/talk.rb
class Talk < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_votable

  has_many :references, dependent: :destroy
  has_and_belongs_to_many :audiences
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :talks, dependent: :destroy

  acts_as_voter

  ANONYMOUS_USERNAME = "anonimo"

  def self.anonymous
    find_or_create_by(username: ANONYMOUS_USERNAME) do |user|
      user.name = "Anônimo"
      user.email = "anonimo@elotalks.com"
    end
  end

  def anonymous?
    self.username == ANONYMOUS_USERNAME
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = UserForm.new(info)

    if !user.new_record?
      flash[:notice] = "Logado com sucesso."
    else
      if user.submit
        flash[:notice] = "Sucesso! Sua conta foi criada com sucesso."
      else
        flash[:error] = "Não foi possível entrar."
      end
    end

    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Você foi deslogado.'
  end

  private

  def info
    info = request.env['omniauth.auth'].info. \
      slice(:nickname, :name, :image, :email)
    user_params = { username: info[:nickname], avatar_url: info[:image], \
      email: info[:email], name: info[:name] || info[:nickname], \
      github_uid: request.env['omniauth.auth'].uid }
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:show]

  def index
    condition = params[:status] == 'past' ? '<' : '>='
    ordering = params[:sort_by] == 'score' ? 'cached_votes_score DESC' : 'deadline ASC'

    @talks = Talk.page(params[:page]). \
      where("deadline #{condition} ?", Date.today).order(ordering). \
      includes(:audiences).decorate
  end

  # GET /talks/:id
  def show
  end

  def slug_available
    render json: { status: Talk.exists?(slug: params[:slug]) }.to_json
  end

  def new
    @talk = TalkForm.new
    @talk.build_reference
    authorize! :create, @talk.record
  end

  def create
    @talk = TalkForm.new(talk_params.merge(user_id: current_user.id))

    if @talk.submit
      redirect_to @talk.record, notice: 'A palestra foi criada com sucesso.'
    else
      @talk.build_reference if @talk.references.empty?
      flash[:alert] = 'A palestra não pode ser salva.'
      render action: 'new'
    end
  end

  private

    def talk_params
      params.require(:talk).permit(:title, :slug, :description, :deadline,
        audience_ids: [],
        nested_audiences_attributes: [:name, :_destroy],
        references_attributes: [:url, :_destroy])
    end

    def set_talk
      @talk = Talk.friendly.find(params[:id]).decorate
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    talk = Talk.friendly.find(params[:talk_id])
    user = current_user || User.anonymous
    service = TalkVoting.new(talk, user, params[:vote])
    service.vote

    redirect_to talk, notice: service.notice
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def errors_for(object, method)
    errors = object.errors[method].collect do |msg|
      content_tag(:li, msg)
    end.join.html_safe

    content_tag(:ul, errors, :class => 'text-error') unless object.errors.empty?
  end

end

app/views/audiences/_audience.html.erb
<li><%= content_tag :span, audience.name, class: "badge" %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Elotalks</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= yield(:scripts) %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-fluid-top navbar-static-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <span class="brand" href="#">Elotalks</span>
        <div class="container-fluid nav-collapse">
          <%= render_navigation level: 1 %>
          <% if current_user %>
            <%= link_to "Sair", log_out_path, class: "pull-right btn btn-danger" %>
            <span class="user-welcome">
              Bem-vindo, <%= content_tag :strong, current_user.name %>!
            </span>
          <% else %>
            <%= link_to "Entrar com Github", '/auth/github', class: "pull-right btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span8 offset2">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/references/_reference.html.erb
<li><%= link_to reference.url, reference.url %></li>

app/views/talks/_form.html.erb
<%= nested_form_for(talk) do |f| %>
  <div class="field">
    <%= f.label :title, class: "control-label" %>
    <%= f.text_field :title, placeholder: "Título da palestra", class: "span9 js-talk-title" %>
    <%= errors_for(f.object, :title) %>
  </div>

  <div class="field field-talk-slug clearfix">
    <%= f.label :slug, class: "control-label" %>
    <div class="input-prepend">
      <%= content_tag :span, "#{talks_url}/", class: "add-on" %>
      <%= f.text_field :slug, placeholder: "titulo-da-palestra", class: "js-talk-slug" %>
    </div>
    <span class="label" id="js-talk-slug-availability-label"></span>
    <%= errors_for(f.object, :slug) %>
  </div>

  <div class="field">
    <%= f.label :description, class: "control-label" %>
    <%= f.text_area :description, placeholder: "Descrição sobre do que se trata a palestra.", class: "span9 wysihtml5", rows: 8 %>
    <%= errors_for(f.object, :description) %>
  </div>

  <div class="field field-talk-audiences">
    <%= f.label :audiences, class: "control-label" %>
    <p>Qual o público alvo?</p>
    <%= f.collection_select(:audience_ids, Audience.all, :id, :name, { include_hidden: false }, multiple: true) %>
    <%= f.fields_for :nested_audiences do |audience_form| %>
      <%= audience_form.text_field :name, placeholder: "Nome para a nova audiência" %>
      <%= audience_form.link_to_remove content_tag(:i, nil, class: "icon-minus"), class: "btn btn-danger" %>
      <%= errors_for(audience_form.object, :name) %>
    <% end %>
    <%= f.link_to_add :nested_audiences, model_object: Audience.new do %>
      <i class="icon-plus"></i> Adicionar uma nova audiência
    <% end %>
    <%= errors_for(f.object, :audiences) %>
  </div>

  <div class="field">
    <%= f.label :deadline, class: "control-label" %>
    <p>Quando deverá ficar pronta?</p>
    <%= f.text_field :deadline, class: "span2 datepicker", placeholder: "DD/MM/AAAA" %>
    <%= errors_for(f.object, :deadline) %>
  </div>

  <div class="field field-talk-references">
    <%= f.label :references, class: "control-label" %>
    <%= f.fields_for :references do |reference_form| %>
      <%= reference_form.text_field :url, class: "span7", placeholder: "http://www..." %>
      <%= reference_form.link_to_remove content_tag(:i, nil, class: "icon-minus"), class: "btn btn-danger" %>
      <%= errors_for(reference_form.object, :url) %>
    <% end %>
    <%= f.link_to_add :references, model_object: Reference.new do %>
      <i class="icon-plus"></i> Adicionar mais um link
    <% end %>
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary pull-right" %>
  </div>
<% end %>

app/views/talks/_talk.html.erb
<li>
  <div class="row-fluid">
    <div class="span2 text-center">
      <div class="well well-small">
        <%= content_tag :span, talk.cached_votes_score, class: "talks-list-score" %>
        <%= "ponto".pluralize talk.cached_votes_score %>
      </div>
      <%= content_tag :strong, talk.deadline, title: "Deadline" %>
    </div>
    <div class="span7">
      <%= link_to talk.title, talk %>
      <%= content_tag :p, truncate(strip_tags(talk.description), length: 200) %>
      <ul class="unstyled inline" title="Audiências">
        <%= render talk.audiences %>
      </ul>
    </div>
    <div class="span3">
      <%= render talk.user %>
    </div>
  </div>
  <hr>
</li>

app/views/talks/index.html.erb
<div class="hero-unit">
  <h1>Elotalks</h1>
  <p>Aqui você pode criar propostas de palestras para eventos e receber avaliações e sugestões dos seus colegas de trabalho.</p>
  <% if can? :create, Talk.new %>
    <%= link_to "Submeta uma palestra", new_talk_path, class: "btn btn-primary btn-large" %>
  <% end %>
</div>

<%= render_navigation level: 2 %>

<div class="talks-sorter text-center">
  <%= render_navigation context: :sorting, renderer: :links %>
</div>

<% if @talks.any? %>
  <ol class="unstyled">
    <%= render @talks %>
  </ol>
<% else %>
  <div class="alert alert-block">
    <h4>Poxa!</h4>
    Nenhuma palestra encontrada.
  </div>
<% end %>

<div class="text-center">
  <%= paginate @talks %>
</div>

app/views/talks/new.html.erb
<div class="page-header">
  <h2>Adicionar palestra</h2>
</div>

<p>Preencha os campos abaixo para adicionar uma nova palestra.</p>

<%= render 'form', talk: @talk %>

app/views/talks/show.html.erb
<%= content_for :scripts do %>
  <%= javascript_include_tag "zeroclipboard" %>
<% end %>

<div class="talk">
  <div class="page-header">
    <%= content_tag :h2, @talk.title, class: "talk-attribute" %>
  </div>

  <div class="row-fluid">
    <div class="span3">
      <%= render @talk.user %>
    </div>
    <div class="span3">
      <%= content_tag :span, t('activemodel.attributes.talk.deadline'), class: "talk-attribute" %>
      <%= content_tag :span, @talk.deadline, class: "talk-deadline" %>
    </div>
    <div class="span6">
      <div class="input-append pull-right">
        <%= content_tag :span, @talk.path, class: "talk-link uneditable-input span4", id: "talk-access-link" %>
        <button class="btn" data-clipboard-target="talk-access-link" id="js-copy-talk-link">
          <i class="icon-copy"></i>
        </button>
      </div>
    </div>
  </div>
  <hr>

  <div class="well">
    <%= raw @talk.description %>
  </div>
  <hr>

  <div class="talk-audiences-wrapper">
    <%= content_tag :h3, t('activemodel.attributes.talk.audiences'), class: "talk-attribute" %>
    <ul class="unstyled inline">
      <%= render @talk.audiences %>
    </ul>
  </div>

  <% if @talk.references.any? %>
    <div class="talk-references-wrapper">
      <%= content_tag :h3, t('activemodel.attributes.talk.references'), class: "talk-attribute" %>
      <ol>
        <%= render @talk.references %>
      </ol>
    </div>
  <% end %>

  <hr>
  <div class="text-center">
    <h4>O que você achou da proposta?</h4>
    <%= form_tag talk_votes_path @talk do %>
      <div class="input-prepend input-append">
        <%= button_tag class: "btn has-tooltip btn-danger #{@talk.vote_active_class("dislike")}", name: "vote", data: { placement: "left" }, title: "-1 ponto", value: @talk.vote_value("dislike") do %>
          <i class="icon-thumbs-down"></i>
        <% end %>
        <%= content_tag :span, pluralize(@talk.cached_votes_score, "ponto"), class: "talk-show-score uneditable-input span2" %>
        <%= button_tag class: "btn has-tooltip btn-primary #{@talk.vote_active_class("like")}", name: "vote", data: { placement: "right" }, title: "+1 ponto", value: @talk.vote_value("like") do %>
          <i class="icon-thumbs-up"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <hr>
</div>

app/views/users/_user.html.erb
criada por:
<div class="media">
  <%= image_tag user.avatar_url, size: "32", class: "pull-left" %>
  <%= content_tag :span, user.name, class: "media-body" %>
</div>